const routes = {
    home: "/",
    following: "/following",
    profile: "/@:nickname",
    upload: "/upload",
    feedback: "/feedback",
    coin: "/coin",
    setting: "/setting",
    explore: "/explore",
    friends: "/friends",
    live: "/live",
    about: "/about",
    contact: "/about/contact",
    forgood: "/forgood",
    business: "/business",
    creatorNetworks: "/live/creator-networks",
    transparency: "/transparency",
    tiktokRewards: "/tiktok-rewards",
    embed: "/embed",
    safety: "/safety",
    termsOfService: "/legal/terms-of-service",
    privacyPolicy: "/legal/privacy-policy-row",
    privacyCenter: "/privacy/overview",
    creatorAcademy: "/creator-academy",
    communityGuidelines: "/community-guidelines",
};

export default routes;
